language: ruby
rvm:
- ruby-head-clang
- ruby-head
- ruby-2.1.2-clang
- ruby-2.1.2
- ruby-2.1.1-clang
- ruby-2.1.1
- ruby-2.1.0-rc1
- ruby-2.1.0-preview2
- ruby-2.1.0-preview1
- ruby-2.1.0
- ruby-2.0.0-p481
- ruby-2.0.0-p451
- ruby-2.0.0-p353
- ruby-2.0.0-p247
- ruby-2.0.0-p195
- ruby-2.0.0-p0
- ruby-1.9.3-p547
- ruby-1.9.3-p545-railsexpress
- ruby-1.9.3-p545
- ruby-1.9.3-p484
- ree-1.8.7-2011.12
- rbx-2.2.7
- rbx-2.2.6
- rbx-2.2.2
- mruby-head
- mruby-1.0.0
- jruby-head
- jruby-1.7.9-d19
- jruby-1.7.11
- jamesgolick
